[package]
name = "maze"
version = "0.1.0"
authors = [ "Boris Faure <billiob@gmail.com>" ]
license = "BSD-2-Clause"

[dependencies]
docopt = "*"
rand = "*"
color_scaling = "0.0.3"
image = "0.7"
gif = "0.8"
debug_macros = "*"
read_color = "*"
