[package]
name = "maze"
version = "0.0.1"
authors = [ "Boris Faure <billiob@gmail.com>" ]
license = "BSD-2-Clause"

[dependencies]
docopt = "*"
rand = "*"
color_scaling = "0.0.2"
image = "0.6"
debug_macros = "*"
read_color = "*"
